### ISSUE TITLE
Problems of <ItemGroup> children nodes

### ISSUE THREAD

**Issue by tamashii** [tintoy/msbuild-project-tools-vscode#148]
There're two problems in `<ItemGroup>` children nodes:
1. The `CopyToOutputPath` attribute is not only available in `<Content>` node, but also available in `<None>`, `<Resource>`, `<EmbeddedResource>` ,`<Compile>` and `<AssemblyMetadata>` node.
2. The three values of `CopyToOutputPath` attribute are `Never`, `Always`, and `PreserveNewest` — but actually is `Newer` in current intellisense hints.

And here's the official document for above content : <https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items>

**Comment by tintoy** [comment]
Thanks for reporting!

1. It should be pretty easy to handle this; I'll look into it tonight.
2. For autocomplete, this should be easy to fix; if the tooltip displayed when hovering says `Newer` then that may be a little trickier because that's what the project system is returning to us. I'll have a look at this tonight, too, if I get time.

**Comment by tintoy** [comment]
Ok, this has been fixed and will be available in the next release 🙂
